# Generated by Django 2.2.7 on 2019-11-07 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.CharField(max_length=7)),
                ('region', models.CharField(max_length=250)),
                ('locality', models.CharField(max_length=250)),
                ('streetAddress', models.CharField(max_length=250)),
                ('extendedAddress', models.CharField(max_length=250)),
            ],
        ),
    ]
